### ISSUE TITLE
Publish vdom.js and its externs as cljsjs package

### ISSUE THREAD

**Issue by ul** [exupero/vdom#1]
It will eliminate manual copying and including of vdom.js

**Comment by neverfox** [comment]
:+1:

**Comment by exupero** [comment]
Thanks for the tip. I'll look into it this week.

**Comment by exupero** [comment]
[Submitted](https://github.com/cljsjs/packages/pull/165).

**Comment by exupero** [comment]
Manual copying is no longer required thanks to `src/deps.cljs`, which specifies the foreign lib and externs.

**Comment by ul** [comment]
Thank you! :+1:
