### ISSUE TITLE
support for keys to avoid rendering issues e.g. with lists

### ISSUE THREAD

**Issue by ghost** [exupero/vdom#4]
I'm implementing the 'todomvc' app in ClojureScript with vdom, and now I have exactly the same issue as described here: https://github.com/elm-lang/virtual-dom/issues/24

The solution would be to mark elements in a list with a unique 'key'. Apparantly this is also supported by virtual-dom:

From https://github.com/Matt-Esch/virtual-dom/blob/master/docs/vnode.md
3rd argument: key (optional)
An identifying string used to differentiate this node from others. Used internally by vtree/diff to do node reordering.

would it be possible to add support for keys to vdom as well?

**Comment by exupero** [comment]
This is now supported via a `:key` value in the attribute map. As in

```
[:div {:key "..."}]
```

Reopen if you have any problems.
